routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Front hand routes goes here*/


Route::group(['namespace'=>'Front'],function(){
    Route::get('/',['as'=>'home','uses'=>'HomeController@index']);
    Route::get('/pricing',['as'=>'pricing','uses'=>'HomeController@pricing']);
    Route::get('login',['as'=>'user','uses'=>'UserController@getlogin']);
    Route::post('login', ['as' => 'login', 'uses' => 'UserController@postLogin']);
   /// Route::get('/user',['as'=>'home','uses'=>'UserController@index']);
  
});

/*Company routes goes here*/

Route::group(['namespace' => 'Company', 'prefix' => 'company'], function() {
    


    Route::group(['middleware' => 'IsNotAuthenticated'], function(){
        Route::get('register', ['as' => 'company.register', 'uses' => 'RegisterController@getRegister']);
        Route::post('register', ['as' => 'company.register', 'uses' => 'RegisterController@postRegister']);
         
        //Route::get('login', ['as' => 'company.login', 'uses' => 'AuthController@getlogin']);
        Route::get('login', ['as' => 'company.login', 'uses' => 'AuthController@getlogin']);
        Route::post('login', ['as' => 'company.login', 'uses' => 'AuthController@postLogin']);
        Route::post('logout', ['as' => 'company.logout', 'uses' => 'AuthController@getLogout']);
        
        //Route::get('otp-verification', ['as' => 'company.otp-verification', 'uses' => 'RegisterController@postOtpVerification']);
        Route::post('otp-verification', ['as' => 'company.otp-verification', 'uses' => 'RegisterController@postOtpVerification']);
        
        Route::get('forgot-password', ['as' => 'company.forgot_password', 'uses' => 'UsersController@forgotPassword']);
        Route::post('forgot-password', ['as' => 'company.forgot_password', 'uses' => 'UsersController@sendPasswordLink']);
        
        Route::get('reset-password/{email_token}', ['as' => 'company.reset_password', 'uses' => 'UsersController@resetPassword']);
        Route::post('reset-password/{email_token}', ['as' => 'company.reset_password', 'uses' => 'UsersController@resetPasswordUpdate']);
    });

    Route::group(['middleware' => 'auth.company'], function() {
        
        // Route::get('/dashboard', function(){
        //     return view('company.dashboard.index');
        //   });
        
        //Route::any('dashboard/{r_id?}/{id?}', ['as' => 'company.dashboard', 'uses' => 'DashboardController@index']);
        Route::any('dashboard', ['as' => 'company.dashboard', 'uses' => 'DashboardController@index']);
        Route::get('change-password', ['as' => 'company.changepassword', 'uses' => 'UsersController@changepassword']);
        Route::post('change-password', ['as' => 'company.updatepassword', 'uses' => 'UsersController@updatepassword']);
        
        Route::resource('roles', 'RoleController', ['names' => [
            'index' => 'admin.roles',
            'create' => 'admin.roles.create',
            'update' => 'admin.roles.update',
            'edit' => 'admin.roles.edit',
            'store' => 'admin.roles.store',
            'destroy' => 'admin.roles.destroy',
        ]]);

        Route::get('role-status-change/{id}/{status}', ['as'=>'admin.roles.status_change','uses' => 'RoleController@status_change']);

        Route::resource('users', 'UsersController', ['names' => [
            'index' => 'admin.users',
            'create' => 'admin.users.create',
            'update' => 'admin.users.update',
            'edit' => 'admin.users.edit',
            'store' => 'admin.users.store',
            'show' => 'admin.users.show',
            'destroy' => 'admin.users.destroy',
        ]]);
        Route::post('users/index', ['as' => 'admin.users.index', 'uses' => 'UsersController@index']);
        
        Route::get('references', ['as'=>'admin.user.references','uses' => 'UsersController@references']);
        Route::get('reference/{id}', ['as'=>'admin.user.reference','uses' => 'UsersController@reference']);


        Route::get('user-status-change/{id}/{status}', ['as'=>'admin.users.status_change','uses' => 'UsersController@status_change']);

        Route::resource('contactus', 'ContactusController', ['names' => [
            'index' => 'admin.contactus',
            'create' => 'admin.contactus.create',
            'update' => 'admin.contactus.update',
            'edit' => 'admin.contactus.edit',
            'store' => 'admin.contactus.store',
            'show' => 'admin.contactus.show',
            'destroy' => 'admin.contactus.destroy',
        ]]);

        Route::get('contactus-status-change/{id}/{status}', ['as'=>'admin.contactus.status_change','uses' => 'ContactusController@status_change']);

        Route::resource('emailtemplates', 'EmailtemplatesController', ['names' => [
            'index' => 'admin.emailtemplates',
            'create' => 'admin.emailtemplates.create',
            'update' => 'admin.emailtemplates.update',
            'edit' => 'admin.emailtemplates.edit',
            'store' => 'admin.emailtemplates.store',
            'show' => 'admin.emailtemplates.show',
            'destroy' => 'admin.emailtemplates.destroy',
        ]]);
        Route::get('emailtemplates-status-change/{id}/{status}', ['as'=>'admin.emailtemplates.status_change','uses' => 'EmailtemplatesController@status_change']);

        Route::resource('settings', 'SettingsController', ['names' => [
            'index' => 'admin.settings',
            'create' => 'admin.settings.create',
            'update' => 'admin.settings.update',
            'edit' => 'admin.settings.edit',
            'store' => 'admin.settings.store',
            'show' => 'admin.settings.show',
            'destroy' => 'admin.settings.destroy',
        ]]);

        Route::resource('cms', 'CmsController', ['names' => [
            'index' => 'admin.cms',
            'create' => 'admin.cms.create',
            'update' => 'admin.cms.update',
            'edit' => 'admin.cms.edit',
            'store' => 'admin.cms.store',
            'show' => 'admin.cms.show',
            'destroy' => 'admin.cms.destroy',
        ]]);

        //plann controller
        Route::resource('plann', 'PlannController', ['names' => [
            'index' => 'admin.plann',
            'create' => 'admin.plann.create',
            'update' => 'admin.plann.update',
            'edit' => 'admin.plann.edit',
            'store' => 'admin.plann.store',
            'show' => 'admin.plann.show',
            'destroy' => 'admin.plann.destroy',
        ]]);

        Route::get('plann-status-change/{id}/{status}', ['as'=>'admin.plann.status_change','uses' => 'PlannController@status_change']);
       

        Route::get('cms-status-change/{id}/{status}', ['as'=>'admin.cms.status_change','uses' => 'CmsController@status_change']);
        
        Route::resource('sliders', 'SlidersController', ['names' => [
            'index' => 'admin.sliders',
            'create' => 'admin.sliders.create',
            'update' => 'admin.sliders.update',
            'edit' => 'admin.sliders.edit',
            'store' => 'admin.sliders.store',
            'show' => 'admin.sliders.show',
            'destroy' => 'admin.sliders.destroy',
        ]]);
        Route::get('slider-status-change/{id}/{status}', ['as'=>'admin.sliders.status_change','uses' => 'SlidersController@status_change']);

        Route::resource('history', 'HistoryController', ['names' => [
            'index' => 'admin.history',
        ]]);

        Route::get('user-history/{id}', ['as'=>'admin.user.history','uses' => 'HistoryController@user_history']);

        Route::resource('industry', 'IndustryController');
        Route::get('industry-status-change/{id}/{status}', ['as'=>'admin.industry.status_change','uses' => 'IndustryController@status_change']);

        Route::resource('product', 'ProductController');
 //Route::post('logout', ['as' => 'logout', 'uses' => 'AuthController@getLogout']);
   
  // Route::get('forgot-password', ['as' => 'forgot_password', 'uses' => 'UsersController@forgotPassword']);
  // Route::post('forgot-password', ['as' => 'forgot_password', 'uses' => 'UsersController@sendPasswordLink']);
   


        Route::resource('price', 'PriceController', ['names' => [
            'index' => 'admin.price',
            'create' => 'admin.price.create',
            'update' => 'admin.price.update',
            'edit' => 'admin.price.edit',
            'store' => 'admin.price.store',
            'show' => 'admin.price.show',
            'destroy' => 'admin.price.destroy',
        ]]);

        Route::get('price-tags', ['as'=>'admin.price.tags','uses' => 'PriceController@price_tags']);


    });
});


/*Admin routes goes here*/

Route::group(['namespace' => 'Admin', 'prefix' => 'admin'], function() {

    Route::group(['middleware' => 'IsNotAuthenticated'], function(){
        
        Route::get('login', ['as' => 'admin.login', 'uses' => 'AuthController@getlogin']);
        Route::post('login', ['as' => 'admin.login', 'uses' => 'AuthController@postLogin']);
        Route::post('logout', ['as' => 'admin.logout', 'uses' => 'AuthController@getLogout']);
        
        Route::get('forgot-password', ['as' => 'admin.forgot_password', 'uses' => 'UsersController@forgotPassword']);
        Route::post('forgot-password', ['as' => 'admin.forgot_password', 'uses' => 'UsersController@sendPasswordLink']);
        
        Route::get('reset-password/{email_token}', ['as' => 'admin.reset_password', 'uses' => 'UsersController@resetPassword']);
        Route::post('reset-password/{email_token}', ['as' => 'admin.reset_password', 'uses' => 'UsersController@resetPasswordUpdate']);
    });

app/Product.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Kyslik\ColumnSortable\Sortable;

class Product extends Model{
   
	use Notifiable,Sortable;

    protected $table = 'products';

    protected $fillable = ['name', 'price', 'title', 'description']; 

    public function photos(){
		return $this->hasMany('App\ProductsPhoto', 'product_id');
    }

    public function industries(){
		return $this->belongsToMany('App\Industry', 'products_industry', 'product_id', 'industry_id')->withPivot('product_id', 'industry_id');
    }

}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Kyslik\ColumnSortable\Sortable;
use Illuminate\Contracts\Auth\CanResetPassword;

class User extends Authenticatable{

    use Notifiable,Sortable;

    protected $table = 'users';

    protected $fillable = ['first_name','last_name','email','phone','role_id','otp','address','status','password','profile_image','company_name','gender','dob','company_url','facebook_token','twitter_token'];  
    
    public function role(){
        return $this->belongsTo('\App\Role','role_id');
    }

    public function refer(){
        return $this->belongsTo('\App\User','refer_id');
    }
}

app/Http/Controllers/Admin/ProductController.php
<?php

namespace App\Http\Controllers\Admin;
use Hash;
use Illuminate\Http\Request;
use App\Http\Requests;
use URL;
use App\Http\Controllers\Controller;
use App\Industry;
use App\Product;
use App\ProductsPhoto;
use App\ProductsIndustry;
use App\EmailTemplate;
use App\Helpers\EmailHelper;
Use DB;
use Session;
use Validator;
use Config;
use Input;
use App\Helpers\BasicFunction;
use Kyslik\ColumnSortable\Sortable;
use Illuminate\Foundation\Auth\AuthenticatesUsers;
use Illuminate\Support\Facades\Auth;
use Illuminate\Auth\Middleware\Authenticate;

class ProductController extends Controller
{
    public function index(Request $request) {

    //http://www.expertphp.in/article/search-and-pagination-with-crud-example-in-laravel-php-framework-and-angularjs	

        $params = $request->all();

    	$per_page =  configure('CONFIG_PAGE_LIMIT');

    	$per_page =  2;

    	if(isset($params['search']) && $params['search'] !=''){
			$word = $params['search'];
            $products = Product::where('name', 'like', '%'.$word.'%')->orderBy('id', 'desc')->paginate($per_page); 
        }else{  
			$products = Product::orderBy('id', 'desc')->paginate($per_page); 
		}	

        $pageTitle = 'Product';
        
        $pages["<i class='fa fa-dashboard'></i>" . 'Dashboard'] = 'admin.dashboard';

        $breadcrumb = array('pages' => $pages, 'active' => "Products");
        setCurrentPage('product.index');
        return view('admin.product.index', compact('products', 'pageTitle', 'title', 'breadcrumb'));
    }

    public function create() {

    	$industries = BasicFunction::getIndustries();
        
        $pageTitle = 'Product';
        $pages["<i class='fa fa-dashboard'></i>" . trans('admin.DASHBOARD')] = 'admin.dashboard';
        $pages['Products'] = 'product.index';
        $breadcrumb = array('pages' => $pages, 'active' => 'Add Product');
        
        return view('admin.product.create', compact('industries', 'pageTitle', 'title', 'breadcrumb'));
    }

    public function store(Request $request) {
    	$rules = [
            'name' => 'required|max:255',
            'photos' => 'required',
        ];

        $msges = array(
            'name.required'=>'Please enter product name',
            'photos.required'=>'Product photo is required',
        );

        $this->validate($request, $rules, $msges);

    	$product = Product::create($request->all());
    	if(isset($request->photos)){
    		foreach ($request->photos as $photo) {
            	$filename = $photo->store('products_photo');
	            ProductsPhoto::create([
	                'product_id' => $product->id,
	                'product_img' => $filename
	            ]);
        	}
    	}
    	
    	if(isset($request->industries) && !empty($request->industries)){
    		for($i=0; $i < count($request->industries); $i++) { 
    			ProductsIndustry::create([
	                'product_id' => $product->id,
	                'industry_id' => $request->industries[$i]
	            ]);
    		}
    	}
    	return redirect()->action('Admin\ProductController@index', getCurrentPage('product.index'))->with('alert-sucess', 'Product added successfully');
    }

    public function edit($id) {

    	if($id == '') {
			return $this->InvalidUrl();
        }
        
        $with = array('photos', 'industries');
        $product = Product::where('id', $id)->with($with)->first();
        
        if(empty($product)){
            return $this->InvalidUrl();
        }

        $industries = BasicFunction::getIndustries();

        $pageTitle = 'Product';
        $pages["<i class='fa fa-dashboard'></i>" . trans('admin.DASHBOARD')] = 'admin.dashboard';
        $pages['Products'] = 'product.index';
        $breadcrumb = array('pages' => $pages, 'active' => 'Edit Product');
        return view('admin.product.edit', compact('product','industries','pageTitle', 'breadcrumb'));
    }


    public function update(Request $request, $id) {

    	$rules = [
            'name' => 'required|max:255',
        ];

        $msges = array(
            'name.required'=>'Please enter product name',
        );

        $this->validate($request, $rules, $msges);

        $product = Product::findOrFail($id);
        $input = $request->all();
        $product->fill($input)->save();

        if($request->img_deleted !=''){
			$imgs = explode(',', $request->img_deleted);
			for($i=0; $i<count($imgs); $i++){
				ProductsPhoto::where('id', $imgs[$i])->delete();	
			}
        }

    	if(isset($request->photos)){
    		foreach ($request->photos as $photo) {
            	$filename = $photo->store('products_photo');
	            ProductsPhoto::create([
	                'product_id' => $product->id,
	                'product_img' => $filename
	            ]);
        	}
    	}
    	
    	ProductsIndustry::where('product_id', $id)->delete();
    	if(isset($request->industries) && !empty($request->industries)){
    		for($i=0; $i < count($request->industries); $i++) { 
    			ProductsIndustry::create([
	                'product_id' => $product->id,
	                'industry_id' => $request->industries[$i]
	            ]);
    		}
    	}
    	return redirect()->action('Admin\ProductController@index', getCurrentPage('product.index'))->with('alert-sucess', 'Product updated successfully');

    }

    public function status_change($id, $status) {

    	if(empty($id)) {
            return $this->InvalidUrl();
        }

        if($status == '1') {
			$new_status = '0';
        }else {
			$new_status = '1';
        }

        $industry = Industry::where('id', '=', $id)->first();
        $industry->status = $new_status;
        $industry->save();

        return redirect()->action('Admin\IndustryController@index', getCurrentPage('industry.index'))->with('alert-sucess', 'Industry status change successfully');
    }
}

resources/views/user/product/create.blade.php
@extends('layouts.admin')

@section('content')
{!! Html::script(asset('public/admin/assets/widgets/ckeditor/ckeditor.js')) !!}
{!! Html::script(asset('public/admin/assets/widgets/multi-select/multiselect.js')) !!} 
<div id="page-content-wrapper">
    <div id="page-content">
        <div class="container">
            <section class="content-header with-border">
                @include('includes.admin.breadcrumb')
            </section>
            <div class="panel">
                <div class="panel-body">
                {!! Form::open(['route'=> 'product.store', 'files' => true, 'id'=>'form_product']) !!} 
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group col-md-6">
                                {!! Form::label('Product Name ',null,['class'=>'col-sm-6 control-label no-padding-right required_label']) !!} 
                                <div class="col-sm-12">
                                    {!! Form::text('name',null,['class'=>'form-control','placeholder'=>'Name']) !!}    
                                </div>
                                <div class="col-sm-12 text-danger">{{ $errors->first('name') }}</div>
                            </div>
                            <div class="form-group col-md-6">
                                {!! Form::label('Product Price ',null,['class'=>'col-sm-6 control-label no-padding-right']) !!} 
                                <div class="col-sm-12">
                                    {!! Form::text('price',null,['class'=>'form-control','placeholder'=>'Price']) !!}    
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">    
                            <div class="form-group col-md-6">
                                {!! Form::label('Product Title ',null,['class'=>'col-sm-6 control-label no-padding-right']) !!} 
                                <div class="col-sm-12">
                                    {!! Form::text('title',null,['class'=>'form-control','placeholder'=>'Title']) !!}    
                                </div>
                            </div>
                        </div>
                    </div>    
                    <div class="row">
                        <div class="form-group col-md-12">
                            {!! Form::label('Product Description',null,['class'=>'col-sm-4']) !!}
                            <div class="col-sm-12">
                                {!! Form::textarea('description',null,['class'=>'form-control ckeditor','placeholder'=>'Description']) !!}
                            </div>
                            <div class="col-sm-12 text-danger">{{ $errors->first('description') }}</div>
                        </div><!-- /.form-group -->
                    </div>

                    <div class="row">

                        <div class="form-group col-md-6">
                            {!! Form::label('Product Image (Max upload 3)',null,['class'=>'col-sm-6']) !!}
                            <div class="col-sm-12">    
                                <div class="table-responsive">  
                                    <table class="table" id="tbl_add_img">  
                                        <tr>  
                                            <td>
                                                <input id="photos" type="file" class="form-control" name="photos[]" multiple maxlength="3">
                                            </td>  
                                        </tr>
                                        <div class="col-sm-12 text-danger">{{ $errors->first('photos') }}</div>  
                                    </table>
                                    <div id="dvPreview"></div>
                                </div>
                            </div>    
                        </div>


                        <!-- <div class="form-group col-md-6">
                            {!! Form::label('Product Image (Max upload 3)',null,['class'=>'col-sm-6']) !!}
                            <div class="col-sm-12">    
                                <div class="table-responsive">  
                                    <table class="table" id="tbl_add_img">  
                                        <tr>  
                                            <td>
                                                <input type="file" class="form-control" name="photos[]">
                                            </td>  
                                            <td>
                                                <button type="button" name="add" id="add" class="btn btn-success">Add More</button>
                                            </td>  
                                        </tr>
                                        <div class="col-sm-12 text-danger">{{ $errors->first('photos') }}</div>  
                                    </table>
                                </div>
                            </div>    
                        </div> -->


                        <div class="col-md-6">

                            <div class="form-group col-sm-12">

{!! Form::label('Product Industries',null,['class'=>'col-sm-4']) !!}


                                <div class="col-sm-12">
                                {{ Form::select('industries[]', $industries, null, ['id'=>'inds', 'class' => 'multi-select', 'multiple'=>true]) }}
                                    
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-actions col-sm-12 center">
                        <div class="col-sm-12">
                        {{Form::button('<i class="fa fa-undo"></i> Reset', array('type' => 'reset', 'class'=> 'btn btn-default btn-sm', 'onclick' => 'this.form.reset();'))}}
                        {{Form::button('<i class="fa fa-save"></i> Save', array('type' => 'submit', 'class'=> 'btn btn-success btn-sm' ))}}
                        </div>
                        <div class="clearfix"></div>
                    </div>
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
</div>

{!! Html::style(asset('public/admin/assets/widgets/multi-select/multiselect.css')) !!}
<style type="text/css">
    #tbl_add_img tr td {
        border: none;
    }
</style>

<script type="text/javascript">
    $(document).ready(function(){ 

        $("#inds").multiSelect();
        $(".ms-container").append('<i class="glyph-icon icon-exchange"></i>');

        var fileUpload = document.getElementById("photos");
        
        fileUpload.onchange = function () {
            if(typeof(FileReader) != "undefined") {
                var dvPreview = document.getElementById("dvPreview");
                dvPreview.innerHTML = "";
                var regex = /^([a-zA-Z0-9\s_\\.\-:])+(.jpg|.jpeg|.gif|.png|.bmp)$/;
                
                for (var i = 0; i < fileUpload.files.length; i++) {
                    var file = fileUpload.files[i];
                    if (regex.test(file.name.toLowerCase())) {
                        var reader = new FileReader();
                        reader.onload = function (e) {
                            var img = document.createElement("IMG");
                            img.height = "100";
                            img.width = "100";
                            img.src = e.target.result;
                            dvPreview.appendChild(img);
                        }
                        reader.readAsDataURL(file);
                    } else {
                        alert(file.name + " is not a valid image file.");
                        dvPreview.innerHTML = "";
                        return false;
                    }
                }    
            } else {
                alert("This browser does not support HTML5 FileReader.");
            }
        }
    });

    /*var i=1;
        $('#add').click(function(){  
           i++;  
           $('#tbl_add_img').append('<tr id="row'+i+'" class="dynamic-added"><td><input type="file" class="form-control" name="photos[]"></td><td><button type="button" name="remove" id="'+i+'" class="btn btn-danger btn_remove">X</button></td></tr>');  
        });  

        $(document).on('click', '.btn_remove', function(){  
           var button_id = $(this).attr("id");   
           $('#row'+button_id+'').remove();  
        });  */  
</script>

<script type="text/javascript">
$(document).ready(function(e){
    /*$('#btn_reset').click(function(){
        $('#form_product')[0].reset();
    });*/            
});
</script>

@endsection

resources/views/user/product/index.blade.php
@extends('layouts.admin')
@section('content') 

<div id="page-content-wrapper">
    <div id="page-content">
        <div class="container">
            <section class="content-header with-border">
                @include('includes.admin.breadcrumb')
            </section>
            <div class="panel">
                <div class="panel-body">
                    <h3 class="title-hero">Product List</h3>
                    <div class="example-box-wrapper">
                        <div class="row">
                            <div class="size-md col-user-left">
                                {!!  Html::decode(Html::link(route('product.create'),"<i class='glyphicon glyphicon-plus'></i> Add New",['class'=>'btn btn-primary btn-md toggle-vis'])) !!}
                            </div>
                            <div class="size-md col-user-right">
                            {!! Form::open(['method'=>'get','route'=>['product.index']]) !!}                         
                                <table class="search_table">
                                  <tbody>
                                    <tr>
                                      <td>{!! Form::text('search', '', ['class'=>'form-control']) !!}</td>
                                      <td><button class="btn btn-primary" type="submit">Search</button></td>
                                    </tr>
                                  </tbody>
                                </table>
                                {!! Form::close() !!}
                            </div>
                        </div>
                        <table id="datatable-responsive" class="table table-striped table-bordered responsive no-wrap" cellspacing="0" width="100%">
                            <thead>
                                <tr>
                                    <th width="10%">S.No.</th>
                                    <th width="15%">@sortablelink('name', 'Name')</th>
                                    <th width="15%">@sortablelink('title', 'Title')</th>
                                    <th width="15%">Price</th>
                                    <th width="15%">Updated At</th>
                                    <th width="20%">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                            @if(!$products->isEmpty())
                                @php $i=1; @endphp
                                @foreach ($products as $product)
                                <tr>
                                    <td>{{$i}}</td>
                                    <td>{{ ucfirst($product->name)}}</td>
                                    <td>{{ ucfirst($product->title)}}</td>
                                    <td>{{ $product->price}}</td>
                                    <td>
                                    {{date('m/d/Y', strtotime($product->updated_at))}}
                                    </td>
                                    <td>
                   
                    {!!  Html::decode(Html::link(route('product.edit', $product->id),"<i class='glyphicon glyphicon-pencil'></i>",['class'=>'btn btn-primary','data-toggle'=>'tooltip','title'=>trans('admin.EDIT')])) !!}

                    {!!  Html::decode(Html::link(route('product.destroy',['id' => $product->id]),"<i class='glyphicon glyphicon-trash'></i>",['class'=>'btn btn-danger confirm_link','data-toggle'=>'tooltip','title'=>'Delete', "data-alert"=>'Delete Product'])) !!}

                                    </td> 
                                </tr>
                                @php $i++; @endphp
                                @endforeach
                            @else
                                <tr>
                                    <td colspan="6">
                                        <div class="data_not_found"> Data Not Found </div>
                                    </td>
                                </tr>
                            @endif
                            </tbody>    
                        </table>
                        {!! $products->appends(Input::all('page'))->render() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<style type="text/css">
    .example-box-wrapper .col-user-left{
        float: left;
        margin-left: 10px;
    }

    .example-box-wrapper .col-user-right{
        float: right;
        margin-right: 10px;
    }
</style>
@endsection